<?php

namespace CrCms\Request\Logger\Tests;

use Illuminate\Contracts\Container\Container;

trait ApplicationTrait
{
    /**
     * @var Container
     */
    public static $app;

    public static function setUpBeforeClass()
    {
        // TODO: Change the autogenerated stub
        parent::setUpBeforeClass();

        static::$app = require __DIR__.'/bootstrap.php';
    }
}
